# Generated by Django 2.1 on 2019-03-14 22:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Credential",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid_token", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("data", django.contrib.postgres.fields.jsonb.JSONField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        )
    ]
