# Generated by Django 2.1 on 2019-02-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credscontent',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
