# Generated by Django 2.1 on 2019-02-25 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_page', '0002_credscontent_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MailContent',
        ),
        migrations.DeleteModel(
            name='UserViewedMail',
        ),
    ]
