# Generated by Django 2.1 on 2019-03-23 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_page', '0003_auto_20190319_0729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credential',
            old_name='data',
            new_name='credentials',
        ),
    ]
