# Generated by Django 2.1 on 2019-02-26 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_page', '0004_auto_20190226_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailmails',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_page.CredsContent'),
        ),
    ]
