# Generated by Django 2.1 on 2019-02-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_page', '0005_gmailmails_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmailmails',
            name='message_id',
            field=models.CharField(max_length=100),
        ),
    ]
