# Generated by Django 2.1 on 2019-02-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_page', '0006_auto_20190226_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmailmails',
            name='come_from',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gmailmails',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gmailmails',
            name='go_to',
            field=models.CharField(max_length=50),
        ),
    ]
