# Generated by Django 2.1 on 2019-03-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_page', '0008_auto_20190226_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailcategory',
            name='css_class',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailcategory',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
