# Generated by Django 2.1 on 2019-03-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_page', '0009_auto_20190303_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailcategory',
            name='css_class',
            field=models.CharField(max_length=30),
        ),
    ]
