# Generated by Django 2.1 on 2019-03-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_page', '0010_auto_20190303_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailmails',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
