# Generated by Django 2.1 on 2019-03-29 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_page', '0004_auto_20190323_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=250)),
                ('cleaned_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('come_from', models.CharField(max_length=250)),
                ('come_from_email', models.CharField(blank=True, max_length=250, null=True)),
                ('go_to', models.CharField(max_length=250)),
                ('go_to_email', models.CharField(blank=True, max_length=250, null=True)),
                ('text_body', models.TextField()),
                ('html_body', models.TextField()),
                ('tag_body', models.TextField()),
                ('snippet', models.TextField()),
                ('blocked', models.BooleanField(default=False)),
                ('viewed', models.BooleanField(default=False)),
                ('favourite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MailCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True)),
                ('css_class', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MailSender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('average', models.FloatField(default=1)),
                ('mail_count', models.IntegerField(default=1)),
                ('is_active', models.BooleanField()),
                ('selected', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mail sender',
                'verbose_name_plural': 'Mail senders',
                'db_table': 'mail_sender',
            },
        ),
        migrations.AddField(
            model_name='mail',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mails.MailCategory'),
        ),
        migrations.AddField(
            model_name='mail',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_page.Credential'),
        ),
    ]
