# Generated by Django 2.1 on 2019-04-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='subject',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
