# Generated by Django 2.1 on 2019-03-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailSender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Mail sender',
                'verbose_name_plural': 'Mail senders',
                'db_table': 'mail_sender',
            },
        ),
    ]
