# Generated by Django 2.1 on 2019-03-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0004_mailsender_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailsender',
            name='average',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='mailsender',
            name='mail_count',
            field=models.IntegerField(default=1),
        ),
    ]
