# Generated by Django 2.1 on 2019-03-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0005_auto_20190323_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='come_from_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mail',
            name='date_mail',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mail',
            name='go_to_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
