# Generated by Django 2.1 on 2019-03-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0007_auto_20190324_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='cleaned_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mailsender',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
