# Generated by Django 2.1 on 2019-03-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0008_auto_20190329_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='come_from',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='mail',
            name='come_from_email',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='date',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='mail',
            name='go_to',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='mail',
            name='go_to_email',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='message_id',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='mailcategory',
            name='css_class',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='mailcategory',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='mailsender',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
